name: Tests

on: [push, pull_request]

jobs:
  run-tests-with-pip:
    name: ${{ matrix.os }}/py${{ matrix.PYTHON_VERSION }}/pip
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    env:
      MPLBACKEND: agg
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        PYTHON_VERSION: [3.8]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}
      - name: Display versions
        run: python -V; pip -V
      - name: Install package
        shell: bash
        run: pip install -U -e .'[doc, tests]'
      - name: Run tests
        run: pytest --cov=kikuchipy --pyargs kikuchipy
      - name: Generate line coverage
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: coverage report --show-missing
      - name: Upload coverage to Coveralls
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: AndreMiras/coveralls-python-action@develop
